
package its340_andreas_anamv;
import java.sql.*;
import javax.swing.*;

/**
 *
 * @author asalg
 */
public class medicalHistory extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(medicalHistory.class.getName());


    /**
     * Creates new form Form1
     */
    public medicalHistory() {
        initComponents();
        
    int testID = 1; 

    // 2. Load the medical data into the fields
    loadMedicalHistoryData(testID); 
    
    // 3. Set the ID field so Save and Navigation work correctly
    lbl_PatientID.setText(String.valueOf("Patient ID: " +testID));

    // 4. Start in locked View Mode (Gray)
    setFormMode(false);
    }
    
    private void loadMedicalHistoryData(int pid) {
    try (Connection conn = dbUtils.ConnectToMySqlDB("root", "")) {
        // Use your medical utility class to fetch the record
        ResultSet rs = medicalHistoryDBUtils.getGeneralMedicalHistory(conn, pid);
        
    if (rs != null && rs.next()) {
        tb_Tobacco.setText(rs.getString("Tobacco"));
        tb_TobaccoQty.setText(rs.getString("TobaccoQuantity"));
        tb_TobaccoDur.setText(rs.getString("Tobaccoduraton")); // Note the SQL typo "duraton"

        tb_Alcohol.setText(rs.getString("Alcohol"));
        tb_AlcoholQty.setText(rs.getString("AlcoholQuantity"));
        tb_AlcoholDur.setText(rs.getString("Alcoholduration"));

        tb_Drug.setText(rs.getString("Drug"));
        tb_DrugType.setText(rs.getString("DrugType"));
        tb_DrugDur.setText(rs.getString("Drugduration")); // Rename this component soon!

        tb_BloodType.setText(rs.getString("BloodType"));
        tb_RH.setText(rs.getString("Rh"));


            JOptionPane.showMessageDialog(this, "Medical History for Patient #" + pid + " loaded.");
        } else {
            JOptionPane.showMessageDialog(this, "No medical history found for Patient ID: " + pid);
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Load Error: " + e.getMessage());
    }
}
    
private String[] getFieldsArray() {
    return new String[]{
        tb_Tobacco.getText(),      // p_Tobacco
        tb_TobaccoQty.getText(),   // p_TobaccoQty
        tb_TobaccoDur.getText(),   // p_TobaccoDur (Added)
        tb_Alcohol.getText(),      // p_Alcohol
        tb_AlcoholQty.getText(),   // p_AlcoholQty
        tb_AlcoholDur.getText(),   // p_AlcoholDur (Added)
        tb_Drug.getText(),         // p_Drug (Added - Yes/No)
        tb_DrugType.getText(),     // p_DrugType
        tb_DrugDur.getText(),     // p_DrugDur (Note: You should rename jTextField4 to tb_DrugDur)
        tb_BloodType.getText(),    // p_BloodType
        tb_RH.getText()            // p_Rh
    };
}

private void updateGUIFromMap(java.util.Map<String, String> results) {
    // This takes the "Answers" from your Map and puts them into the text boxes
    tb_Tobacco.setText(results.getOrDefault("Tobacco", "No"));
    tb_TobaccoQty.setText(results.getOrDefault("TobaccoQuantity", "N/A"));
    tb_TobaccoDur.setText(results.getOrDefault("Tobaccoduraton", "N/A"));

    tb_Alcohol.setText(results.getOrDefault("Alcohol", "No"));
    tb_AlcoholQty.setText(results.getOrDefault("AlcoholQuantity", "N/A"));
    tb_AlcoholDur.setText(results.getOrDefault("Alcoholduration", "N/A"));

    tb_Drug.setText(results.getOrDefault("Drug", "No"));
    tb_DrugType.setText(results.getOrDefault("DrugType", "N/A"));
    tb_DrugDur.setText(results.getOrDefault("Drugduration", "N/A"));

    tb_BloodType.setText(results.getOrDefault("BloodType", "N/A"));
    tb_RH.setText(results.getOrDefault("Rh", "N/A"));
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tb_Tobacco = new javax.swing.JTextField();
        tb_TobaccoQty = new javax.swing.JTextField();
        tb_Alcohol = new javax.swing.JTextField();
        tb_AlcoholQty = new javax.swing.JTextField();
        tb_DrugType = new javax.swing.JTextField();
        tb_BloodType = new javax.swing.JTextField();
        tb_RH = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnNew = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        lblModeStatus = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btn_StartInterview = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        lbl_PatientID = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tb_TobaccoDur = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tb_AlcoholDur = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tb_Drug = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tb_DrugDur = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        tb_Tobacco.setText("jTextField1");
        tb_Tobacco.addActionListener(this::tb_TobaccoActionPerformed);

        tb_TobaccoQty.setText("jTextField2");

        tb_Alcohol.setText("jTextField3");

        tb_AlcoholQty.setText("jTextField4");

        tb_DrugType.setText("jTextField5");

        tb_BloodType.setText("jTextField6");

        tb_RH.setText("jTextField7");

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Tobacco:");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Tobacco Quantity:");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Alcohol:");

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Alcohol Quantity:");

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Drug Type:");

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Blood Type:");

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Rh:");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        btnNew.setText("New");
        btnNew.addActionListener(this::btnNewActionPerformed);

        btnEdit.setText("Edit");
        btnEdit.addActionListener(this::btnEditActionPerformed);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);

        lblModeStatus.setForeground(new java.awt.Color(0, 0, 0));
        lblModeStatus.setText("Mode:");

        btnSave.setText("Save");
        btnSave.addActionListener(this::btnSaveActionPerformed);

        btn_StartInterview.setText("Start Interview");
        btn_StartInterview.setToolTipText("");
        btn_StartInterview.addActionListener(this::btn_StartInterviewActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblModeStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnNew)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnEdit))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnSave)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnDelete)))
                        .addGap(29, 29, 29))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(btn_StartInterview, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lblModeStatus)
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNew)
                    .addComponent(btnEdit))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnDelete))
                .addGap(18, 18, 18)
                .addComponent(btn_StartInterview, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addGap(8, 8, 8))
        );

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("General Medical History");

        btnBack.setText("Back");
        btnBack.addActionListener(this::btnBackActionPerformed);

        btnNext.setText("Next");
        btnNext.addActionListener(this::btnNextActionPerformed);

        lbl_PatientID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_PatientID.setForeground(new java.awt.Color(0, 0, 0));
        lbl_PatientID.setText("Patient ID:");

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Tabacco Duration: ");

        tb_TobaccoDur.setText("jTextField1");

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Alcohol Duration: ");
        jLabel10.setToolTipText("");

        tb_AlcoholDur.setText("jTextField2");

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Drugs: ");

        tb_Drug.setText("jTextField3");

        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Drug Duration: ");
        jLabel12.setToolTipText("");

        tb_DrugDur.setText("jTextField4");
        tb_DrugDur.addActionListener(this::tb_DrugDurActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 520, Short.MAX_VALUE)
                        .addComponent(btnNext))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tb_Tobacco, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                    .addComponent(tb_TobaccoQty)
                                    .addComponent(tb_Alcohol)
                                    .addComponent(tb_AlcoholQty)
                                    .addComponent(tb_AlcoholDur)
                                    .addComponent(tb_TobaccoDur))))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lbl_PatientID, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(tb_Drug, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(tb_DrugType, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tb_BloodType, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                            .addComponent(tb_RH, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                            .addComponent(tb_DrugDur))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lbl_PatientID))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tb_Tobacco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11)
                        .addComponent(tb_Drug, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tb_TobaccoQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(tb_DrugType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tb_TobaccoDur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(tb_DrugDur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tb_Alcohol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(tb_BloodType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tb_AlcoholQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(tb_RH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tb_AlcoholDur, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(126, 126, 126))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnNext))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void setFormMode(boolean isEditable) {
    // Determine the color based on the mode
    java.awt.Color bgColor = isEditable ? java.awt.Color.WHITE : new java.awt.Color(240, 240, 240); // White if editable, light gray if locked

    // Add all the new fields to this array
        JTextField[] fields = {
        tb_Tobacco, tb_TobaccoQty, tb_TobaccoDur, 
        tb_Alcohol, tb_AlcoholQty, tb_AlcoholDur, 
        tb_Drug, tb_DrugType, tb_DrugDur, 
        tb_BloodType, tb_RH
    };
    
    for (JTextField field : fields) {
        field.setEditable(isEditable);
        field.setBackground(bgColor);
    }

    // Toggle Buttons
    btnSave.setEnabled(isEditable);
    btnEdit.setEnabled(!isEditable);
    btnNew.setEnabled(!isEditable);
    btnDelete.setEnabled(!isEditable);

    // Update Status Label
    lblModeStatus.setText(isEditable ? "Mode: Edit" : "Mode: View (Locked)");
}
    private void tb_TobaccoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_TobaccoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tb_TobaccoActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
    // 1. Clear all fields for a fresh entry
        tb_Tobacco.setText("");
        tb_TobaccoQty.setText("");
        tb_Alcohol.setText("");
        tb_AlcoholQty.setText("");
        tb_DrugType.setText("");
        tb_BloodType.setText("");
        tb_RH.setText("");
        tb_TobaccoDur.setText("");
        tb_AlcoholDur.setText("");
        tb_Drug.setText("");
        tb_DrugDur.setText("");

        // 2. Change the form to "Edit" mode (This will turn them white and editable)
        setFormMode(true);

    }//GEN-LAST:event_btnNewActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        setFormMode(true);
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
// 1. Safety Check: Make sure a record is actually loaded
    String rawID = lbl_PatientID.getText().trim();
    if (rawID.equals("Patient ID:") || rawID.isEmpty()) {
        JOptionPane.showMessageDialog(this, "No medical history record is currently selected.");
        return;
    }

    // 2. Confirm Deletion (Medical records should never be deleted by accident!)
    int confirm = JOptionPane.showConfirmDialog(this,
        "Are you sure you want to mark this medical history as DELETED?\n" +
        "This will deactivate the record in the system.",
        "Confirm Soft Delete",
        JOptionPane.YES_NO_OPTION,
        JOptionPane.WARNING_MESSAGE);

    if (confirm == JOptionPane.YES_OPTION) {
        try (Connection conn = dbUtils.ConnectToMySqlDB("root", "")) {
            // FIX: Remove the label prefix so we can parse the number safely
            String pidText = rawID.replace("Patient ID:", "").trim();
            int pid = Integer.parseInt(pidText);

            // 3. Call your utility method
            int result = medicalHistoryDBUtils.deleteGeneralMedicalHistory(conn, pid);

            if (result >= 0) {
                JOptionPane.showMessageDialog(this, "Medical record successfully deactivated.");

                // 4. Clear the form and lock it (reusing your New button logic)
                btnNewActionPerformed(null);
                setFormMode(false);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Delete Error: " + e.getMessage());
        }
    }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
       // navigationUtils.switchForm(this, new partner2form?());
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        navigationUtils.switchForm(this, new patientDemographics());
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        // 1. Validation
    if (!validationUtils.isNotEmpty(tb_BloodType, "Blood Type")) return;
    if (!validationUtils.matchesPattern(tb_RH, "Rh", "[+-]", "+ or -")) return;

    // 2. Database Operation
    try (Connection conn = dbUtils.ConnectToMySqlDB("root", "")) {
        System.out.println("ID Label Text: " + lbl_PatientID.getText());
        // Strip non-numeric characters from the label
        int pid = Integer.parseInt(lbl_PatientID.getText().replaceAll("[^0-9]", ""));
        
        // Get our suitcase of data
        String[] medicalData = getFieldsArray();
        
        // Pass the array to the DB Utils
        int result = medicalHistoryDBUtils.upsertGeneralMedicalHistory(conn, pid, medicalData);

        if (result >= 0) {
            JOptionPane.showMessageDialog(this, "Medical Record Saved!");
            setFormMode(false); 
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Save Failed: " + e.getMessage());
    }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void tb_DrugDurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_DrugDurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tb_DrugDurActionPerformed

    private void btn_StartInterviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_StartInterviewActionPerformed
    // 1. Get ID
        int pid = Integer.parseInt(lbl_PatientID.getText().replaceAll("[^0-9]", ""));

        // 2. Run the interview
        java.util.Map<String, String> interviewResults = InterviewUtils.runMedicalHistoryInterview(pid);

        if (interviewResults != null && !interviewResults.isEmpty()) {

            // --- THIS PART HANDLES THE TXT FILE SAVING ---

            // A. Build the Question/Answer string for the file
            StringBuilder logContent = new StringBuilder();
            for (java.util.Map.Entry<String, String> entry : interviewResults.entrySet()) {
                logContent.append("Question/Field: ").append(entry.getKey())
                          .append(" -> Answer: ").append(entry.getValue())
                          .append("\n");
            }

            // B. Call the Log Class to create the .txt file
            // This is where the 'magic' happens for Requirement 1.c
            String pName = "Patient #" + pid; // Use your name label here if you have one
            logUtils.writeInterviewLog(pid, pName, "GeneralMedicalHistory", logContent.toString());

            // ----------------------------------------------

            // C. Update the GUI text boxes (so you can see them on screen)
            updateGUIFromMap(interviewResults); 

            setFormMode(true); // Unlock the form
            JOptionPane.showMessageDialog(this, "Interview Logged to Text File and Form Updated!");
        }
    }//GEN-LAST:event_btn_StartInterviewActionPerformed

    /**
     * @param args the command line arguments
     */
 public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new medicalHistory().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btn_StartInterview;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblModeStatus;
    private javax.swing.JLabel lbl_PatientID;
    private javax.swing.JTextField tb_Alcohol;
    private javax.swing.JTextField tb_AlcoholDur;
    private javax.swing.JTextField tb_AlcoholQty;
    private javax.swing.JTextField tb_BloodType;
    private javax.swing.JTextField tb_Drug;
    private javax.swing.JTextField tb_DrugDur;
    private javax.swing.JTextField tb_DrugType;
    private javax.swing.JTextField tb_RH;
    private javax.swing.JTextField tb_Tobacco;
    private javax.swing.JTextField tb_TobaccoDur;
    private javax.swing.JTextField tb_TobaccoQty;
    // End of variables declaration//GEN-END:variables
}
