package its340_andreas_anamv;
import DBUtils.DBConnection;
import utils.FormUtils;
import utils.SOBInterviewUtils;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.JTextComponent;
import java.sql.*;
import java.util.Map;

public class SOBForm extends javax.swing.JFrame {
    int selectedID = -1;
    JTextComponent[] fields;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SOBForm.class.getName());

    public SOBForm() {
        initComponents();
        fields = new JTextComponent[]{
                txtSeverity,
                txtNotes,
                txtDate
        };

        tblSOB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSOBMouseClicked(evt);
            }
        });

        loadTable();
    }
    
    private void loadTable() {
        try {
            Connection con = DBConnection.getConnection();

            String sql = "SELECT SOBID, SOBDate, Severity, Notes FROM sobtable WHERE PatientID=?";
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setInt(1, SelectedPatient.patientID);

            ResultSet rs = ps.executeQuery();

            DefaultTableModel model = new DefaultTableModel();
            model.setColumnIdentifiers(new String[]{"ID", "Date", "Severity", "Notes"});

            while (rs.next()) {
                model.addRow(new Object[]{
                        rs.getInt("SOBID"),
                        rs.getDate("SOBDate"),
                        rs.getString("Severity"),
                        rs.getString("Notes")
                });
            }

            tblSOB.setModel(model);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    private void tblSOBMouseClicked(java.awt.event.MouseEvent evt) {
        int row = tblSOB.getSelectedRow();

        selectedID = Integer.parseInt(tblSOB.getValueAt(row, 0).toString());

        txtDate.setText(tblSOB.getValueAt(row, 1).toString());
        txtSeverity.setText(tblSOB.getValueAt(row, 2).toString());
        txtNotes.setText(tblSOB.getValueAt(row, 3).toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtSeverity = new javax.swing.JTextField();
        txtDate = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtNotes = new javax.swing.JTextArea();
        btnNew = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnInterview = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblSOB = new javax.swing.JTable();

        jButton5.setText("jButton5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Severity");

        jLabel2.setText("Notes");

        jLabel3.setText("Date (YYYY-MM-DD)");

        txtNotes.setColumns(20);
        txtNotes.setRows(5);
        jScrollPane1.setViewportView(txtNotes);

        btnNew.setText("New");
        btnNew.addActionListener(this::btnNewActionPerformed);

        btnEdit.setText("Edit");
        btnEdit.addActionListener(this::btnEditActionPerformed);

        btnSave.setText("Save");
        btnSave.addActionListener(this::btnSaveActionPerformed);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);

        btnInterview.setText("Interview");
        btnInterview.addActionListener(this::btnInterviewActionPerformed);

        tblSOB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblSOB);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDate)
                                    .addComponent(txtSeverity))
                                .addGap(60, 60, 60)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(btnNew)
                                .addGap(51, 51, 51)
                                .addComponent(btnEdit)
                                .addGap(63, 63, 63)
                                .addComponent(btnSave)
                                .addGap(58, 58, 58)
                                .addComponent(btnDelete)
                                .addGap(61, 61, 61)
                                .addComponent(btnInterview)))
                        .addContainerGap(80, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtSeverity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnEdit)
                        .addComponent(btnNew))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSave)
                        .addComponent(btnDelete)
                        .addComponent(btnInterview)))
                .addGap(49, 49, 49)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(169, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        FormUtils.clearAndEdit(fields);
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
       try {
        if (txtSeverity.getText().trim().isEmpty() ||
            txtDate.getText().trim().isEmpty()) {

            JOptionPane.showMessageDialog(this, "All fields are required!");
            return;
        }

        try {
            java.sql.Date.valueOf(txtDate.getText().trim());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Invalid date format (YYYY-MM-DD)");
            return;
        }

        Connection con = DBConnection.getConnection();

        if (selectedID == -1) {

            PreparedStatement ps = con.prepareStatement(
                "INSERT INTO sobtable (PatientID, SOBDate, Severity, Notes) VALUES (?, ?, ?, ?)"
            );

            ps.setInt(1, SelectedPatient.patientID);
            ps.setDate(2, java.sql.Date.valueOf(txtDate.getText().trim()));
            ps.setString(3, txtSeverity.getText().trim());
            ps.setString(4, txtNotes.getText().trim());

            ps.executeUpdate();

        } else {

            PreparedStatement ps = con.prepareStatement(
                "UPDATE sobtable SET SOBDate=?, Severity=?, Notes=? WHERE SOBID=?"
            );

            ps.setDate(1, java.sql.Date.valueOf(txtDate.getText().trim()));
            ps.setString(2, txtSeverity.getText().trim());
            ps.setString(3, txtNotes.getText().trim());
            ps.setInt(4, selectedID);

            ps.executeUpdate();
        }

        JOptionPane.showMessageDialog(this, "Saved successfully!");

        loadTable();
        FormUtils.clearAndEdit(fields);
        selectedID = -1;

    } catch (Exception e) {
        e.printStackTrace();
    }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        try {
        if (selectedID == -1) {
            JOptionPane.showMessageDialog(this, "Select a row first");
            return;
        }

        Connection con = DBConnection.getConnection();

        PreparedStatement ps = con.prepareStatement(
            "DELETE FROM sobtable WHERE SOBID=?"
        );

        ps.setInt(1, selectedID);
        ps.executeUpdate();

        JOptionPane.showMessageDialog(this, "Deleted successfully!");

        loadTable();
        FormUtils.clearAndEdit(fields);
        selectedID = -1;

    } catch (Exception e) {
        e.printStackTrace();
    }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnInterviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInterviewActionPerformed
       Map<String, String> results = SOBInterviewUtils.runSOBInterview();

    txtSeverity.setText(results.get("Severity"));
    txtNotes.setText(results.get("Notes"));
    }//GEN-LAST:event_btnInterviewActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        FormUtils.clearAndEdit(fields);
    }//GEN-LAST:event_btnEditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SOBForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnInterview;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblSOB;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextArea txtNotes;
    private javax.swing.JTextField txtSeverity;
    // End of variables declaration//GEN-END:variables
}
